apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bottlerocket
  region: us-east-2

managedNodeGroups: []

nodeGroups:
  - name: ng1
    instanceType: t3.xlarge
    minSize: 3
    maxSize: 6
    privateNetworking: true
    amiFamily: Bottlerocket
    disablePodIMDS: true
    labels:
      bottlerocket.aws/updater-interface-version: 1.0.0
    iam:
       attachPolicyARNs:
          - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
          - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
          - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
          - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    bottlerocket:
      settings:
        motd: "Example Bottlerocket Deployment!"
