apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bottlerocket
  region: us-east-2

managedNodeGroups: []

nodeGroups:
  - name: ng1
    instanceType: t3.xlarge
    minSize: 3
    maxSize: 6
    privateNetworking: true
    amiFamily: Bottlerocket
    ami: auto-ssm
    labels:
      bottlerocket.aws/updater-interface-version: 2.0.0
    ssh:
      allow: true
      publicKeyName: alexrhea
    iam:
       attachPolicyARNs:
          - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
          - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
          - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
          - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    bottlerocket:
      enableAdminContainer: true
      settings:
        motd: "Example Bottlerocket Deployment!"
