apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fargate
  region: us-east-2

managedNodeGroups: []

fargateProfiles:

  - name: fp-default
    selectors:
      - namespace: default

  - name: fp-kube-system
    selectors:
      - namespace: kube-system
